---
title: "Calculate Distances"
author: "Annie Bryant"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F)
```

```{r}
library(oro.nifti)
library(tidyverse)
library(neurobase)
library(freesurferformats)
library(ggpubr)
library(colorspace)
library(ggplotify)
library(EBImage)
library(icesTAF)
library(knitr)
library(kableExtra)
library(readxl)
library(forcats)
rm(list=ls())
```


```{r}
freesurfer_codes <- read_excel("../FreeSurfer/FS_Codes.xlsx")
```

```{r}
aseg.mni.fs <- img_colour_df(readNIfTI("../FreeSurfer/aparc+aseg.nii.gz")) %>%
  select(-zi, -colour) %>% 
  rename("x"="dim1", "y"="dim2", "z"="dim3", "Index"="value") %>%
  filter(Index>1) %>%
  left_join(., freesurfer_codes)
aparc.aseg.2009s.mni <- img_colour_df(readNIfTI("../FreeSurfer/aparc.a2009s+aseg.nii.gz")) %>%
  select(-zi, -colour) %>% 
  rename("x"="dim1", "y"="dim2", "z"="dim3", "Index"="value") %>%
  filter(Index>1) %>%
  left_join(., freesurfer_codes)
```

```{r}
aseg.mni.fs.centroids <- aseg.mni.fs %>%
  filter(!is.na(FS_Name)) %>%
  group_by(Index, FS_Name, Description) %>%
  summarise(Centroid_x = mean(x), Centroid_y=mean(y), Centroid_z=mean(z)) %>%
  ungroup() %>%
  filter(!(Index %in% c(1000, 2000))) %>%
  select(-Index, -Description) %>%
  rename("ROI1" = "FS_Name")

aseg.mni.fs.dists <- as.data.frame(t(combn(aseg.mni.fs.centroids$ROI1, m=2))) %>%
  rename("ROI1" = "V1", "ROI2" = "V2") %>%
  left_join(aseg.mni.fs.centroids) %>%
  left_join(aseg.mni.fs.centroids, by=c("ROI2"="ROI1"), suffix=c("1", "2")) %>%
  group_by(ROI1, ROI2) %>%
  summarise(Euclidean_Distance = sqrt(sum( (Centroid_x1-Centroid_x2)^2 + (Centroid_y1-Centroid_y2)^2 + (Centroid_z1-Centroid_z2)^2 ))) %>%
  mutate(smushed = ifelse(ROI1<ROI2, paste(ROI1, ROI2, sep="_"),
         paste(ROI2, ROI1, sep="_")))


aparc.aseg.mni.fs.centroids <- aparc.aseg.2009s.mni %>%
  filter(!is.na(FS_Name)) %>%
  group_by(Index, FS_Name, Description) %>%
  summarise(Centroid_x = mean(x), Centroid_y=mean(y), Centroid_z=mean(z)) %>%
  ungroup() %>%
  filter(!(Index %in% c(11100, 12100))) %>%
  select(-Index, -Description) %>%
  rename("ROI1" = "FS_Name")

aparc.aseg.mni.fs.dists <- as.data.frame(t(combn(aparc.aseg.mni.fs.centroids$ROI1, m=2))) %>%
  rename("ROI1" = "V1", "ROI2" = "V2") %>%
  left_join(aparc.aseg.mni.fs.centroids) %>%
  left_join(aparc.aseg.mni.fs.centroids, by=c("ROI2"="ROI1"), suffix=c("1", "2")) %>%
  group_by(ROI1, ROI2) %>%
  summarise(Euclidean_Distance = sqrt(sum( (Centroid_x1-Centroid_x2)^2 + (Centroid_y1-Centroid_y2)^2 + (Centroid_z1-Centroid_z2)^2 ))) %>%
  mutate(smushed = ifelse(ROI1<ROI2, paste(ROI1, ROI2, sep="_"),
         paste(ROI2, ROI1, sep="_")))

fs.roi.euc.dists <- plyr::rbind.fill(aparc.aseg.mni.fs.dists, aseg.mni.fs.dists) %>% distinct()

  
```






```{r}
dti_conn_df <- read_excel("../Data/fiber_counts_fs_ROI.xlsx", sheet=2) %>%
  rename("ROI1"="...1") %>%
  pivot_longer(cols=c(-ROI1), names_to="ROI2", values_to="n_Fiber_Conns")

dti_aparc <- read_excel("../Data/fiber_counts_fs_ROI.xlsx", sheet=1) %>%
  rename("ROI1"="...1") %>%
  pivot_longer(cols=c(-ROI1), names_to="ROI2", values_to="n_Fiber_Conns")

dti_conn_df <- rbind(dti_conn_df, dti_aparc) %>%
  filter(ROI1 != ROI2) %>%
  mutate(smushed = ifelse(ROI1<ROI2, paste(ROI1, ROI2, sep="_"),
         paste(ROI2, ROI1, sep="_"))) %>%
  distinct(smushed, .keep_all = T) %>%
  filter(str_detect(ROI1, "[u|U]nknown", negate=T),
         str_detect(ROI2, "[u|U]nknown", negate=T))
```


```{r}
mega_roi_df <- dti_conn_df %>%
  select(-ROI1, -ROI2) %>%
  left_join(., fs.roi.euc.dists, by=c("smushed")) %>%
  select(ROI1, ROI2, n_Fiber_Conns, Euclidean_Distance)
```

