---
title: "Load_Segstats"
author: "Annie Bryant"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
read_aparc_segstats <- function(subj) {
  s_pet <- read.table(sprintf("../../Not_for_Github/aparc_aseg_stats/%s_TauPET_aparc_aseg_stats.txt", subj),  skip=54)
  colnames(s_pet) <- c("RowNum", "SegId", "NVoxels", "Volume_mm3", "ROI_Name", "Mean_Intensity", "SD_Intensity", "Min_Intensity", "Max_Intensity", "Range_Intensity")
  s_pet$Modality <- "Tau_PET"
  
  s_asl <- read.table(sprintf("../../Not_for_Github/aparc_aseg_stats/%s_perfusion_fsT1_stats.txt", subj),  skip=54)
  colnames(s_asl) <- c("RowNum", "SegId", "NVoxels", "Volume_mm3", "ROI_Name", "Mean_Intensity", "SD_Intensity", "Min_Intensity", "Max_Intensity", "Range_Intensity")
  s_asl$Modality <- "ASL_CBF"
  
  s_cbf <- read.table(sprintf("../../Not_for_Github/aparc_aseg_stats/%s_SE_OEF_parametric_lc_CBF_fsT1_stats.txt", subj),  skip=54)
  colnames(s_cbf) <- c("RowNum", "SegId", "NVoxels", "Volume_mm3", "ROI_Name", "Mean_Intensity", "SD_Intensity", "Min_Intensity", "Max_Intensity", "Range_Intensity")
  s_cbf$Modality <- "SE_DSC_CBF"
  
  s_cth <- read.table(sprintf("../../Not_for_Github/aparc_aseg_stats/%s_SE_OEF_parametric_lc_FH_fsT1_stats.txt", subj),  skip=54)
  colnames(s_cth) <- c("RowNum", "SegId", "NVoxels", "Volume_mm3", "ROI_Name", "Mean_Intensity", "SD_Intensity", "Min_Intensity", "Max_Intensity", "Range_Intensity")
  s_cth$Modality <- "SE_DSC_CTH"
  
  s_pet$Subject <- s_asl$Subject <- s_cbf$Subject <- s_cth$Subject <- subj
  
  aparc_aseg_stats <<- do.call(plyr::rbind.fill,
                               list(aparc_aseg_stats, s_pet, s_asl, s_cbf,
                                    s_cth)) %>% select(-RowNum)
  
}
```


```{r}
aparc_aseg_stats <- data.frame()
for (subj in paste("AD0", 1:7, sep="")) {
  read_aparc_segstats(subj)
}
```

